version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    # Remova o volume ou configure como abaixo
    # volumes:
    #   - .:/app:cached
    #   - /app/node_modules
    environment:
      - NODE_ENV=development
    command: pnpm start
